FROM postgres:11.2-alpine

#COPY docker-entrypoint-initdb.d/init-cright-db.sh /docker-entrypoint-initdb.d/init_cright_db.sh
#CMD psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d notebook-symfony -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
#CMD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB" -c 'CREATE SCHEMA IF NOT EXISTS coupons-parser;'
#CMD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

#RUN docker-entrypoint-initdb.d/init_cright_db.sh
