version: '3'
services:
    postgres:
        image: postgres:11
#        build: Docker/postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: coupons-parser
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

 #       volumes:
 #           - ./Docker/postgres/pgdata:/var/lib/postgresql/data
        networks:
          coupons-parser-network:
                aliases:
                    - coupons-parser-network
    php:
        build: Docker/php-fpm
        restart: always
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/coupons-parser
            #- ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/coupons-parser
        links:
            - postgres
            - proxy
        networks:
          coupons-parser-network:
                aliases:
                    - coupons-parser-network
    nginx:
        build: Docker/nginx
        restart: always
        ports:
            - '8080:80'
            - '443:443'
        links:
            - php
        volumes:
            - ./:/var/www/coupons-parser
            - ./nginxlog:/var/log/nginx
        networks:
            coupons-parser-network:
                aliases:
                    - coupons-parser-network
    proxy:
        build: Docker/proxy1
        restart: always
#        ports:
#            - '8119:8118'
#            - '9081:9080'
        networks:
            coupons-parser-network:
                 aliases:
                    - coupons-parser-network

networks:
    coupons-parser-network:
        driver: bridge
